### ISSUE TITLE
Fist try, error

### ISSUE THREAD

**Issue by matiasdecarli** [aws-quickstart/quickstart-atlassian-jira#11]
I've followed the steps on the guide and get the stack created

<img width="1411" alt="screen shot 2017-06-22 at 12 43 57 pm" src="https://user-images.githubusercontent.com/2442390/27443166-9448b18e-5748-11e7-981d-87b0d5dc9e66.png">

Then, when I go to the OUTPUT section, both urls (JiraURL, LoadBalancerURL) gave me this error

<img width="929" alt="screen shot 2017-06-22 at 12 44 19 pm" src="https://user-images.githubusercontent.com/2442390/27443186-a9b5b102-5748-11e7-9c78-1004c5395852.png">

How can I debug this? I followed all the necessary steps and ended up in this error

**Comment by matiasdecarli** [comment]
Ok, so apparently the creation process wasn't finished yet. After some minutes it started to work

**Comment by dikeert** [comment]
Hello @matiasdecarli!

Unfortunately JIRA's installation process takes some time. You can monitor JIRA's availability in load balancer UI - it'll indicate whenever node is in healthy state. If I remember correctly you need to click load balancer link in resources section and switch to "instances" tab. I can run a stack myself and provide you with detailed instruction if you need so.
