### ISSUE TITLE
Template does not work in non-internet enabled VPCs

### ISSUE THREAD

**Issue by aggallim** [aws-quickstart/quickstart-atlassian-jira#12]
We're trying to use the 'deploy into existing VPC' template to deploy into our VPCs which do not have internet access. 

The AMI makes a call out to S3 (https://s3.amazonaws.com/atlassian-software/snapshots/jira/atlassian-jira-software-x64.bin) to download the software. This is unusable via the AWS S3 endpoint unless the template is built in a region the same as the S3 bucket. A way around this would be to parameterize the S3 bucket url so customers can specify their own bucket.

**Comment by dikeert** [comment]
Hello, @aggallim! It seems that you're trying to use some kind of old version of this template. Could you please confirm that you're using the latest template from the master branch? We've updated the template long time ago to not use snapshot versions of JIRA but I can see from the URL that your template is trying to do that. If you're dead sure that you're using the latest version of template, please, create a gist with this template inside and ping it to me, I'll check it.

Thank you!

**Comment by aggallim** [comment]
Thanks for pointing that out @dikeert , it turns out we've been working from a template with the description  "QS(0035) Atlassian Jira Data Center Nov,23,2016". I'll take a look at the latest to see if this works.

**Comment by avattathil** [comment]
Closing this ticket please reopen if you need further assistance
