### ISSUE TITLE
Missing ingress port rule for postgres?

### ISSUE THREAD

**Issue by et304383** [aws-quickstart/quickstart-atlassian-jira#13]
I might be missing something, but I don't see where a rule has been added to SecurityGroup to let traffic in on port 5432 or something similar.

**Comment by dikeert** [comment]
We put RDS into same subnet with JIRA, why would we need this rule?

**Comment by et304383** [comment]
Subnets have nothing to do with firewall rules.  You still need a rule allowing traffic for port 5432 into the RDS from the EC2 server running JIRA server.

**Comment by dikeert** [comment]
Hello, @et304383! Sorry for long response, I'm not doing it on full time bases.

We're using VPC Security Group in line with [this documentation](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-rds-database-instance.html#cfn-rds-dbinstance-vpcsecuritygroups):


```json
"VPCSecurityGroups": [
    {
        "Ref": "SecurityGroup"
    }
]
```

**Comment by et304383** [comment]
I get how to fix it @dikeert .  I'm simply stating that the quick start doesn't work out of the box because of this missing rule to allow the incoming traffic to postgres.

It can easily be seen here that the SecurityGroup object you're referencing has no rule to allow incoming postgres traffic:

https://github.com/aws-quickstart/quickstart-atlassian-jira/blob/develop/templates/JiraDataCenter.template#L1003

I have reviewed the template to determine if maybe public access was being relied on, but since it has a DB Subnet Group specified this should not be the case.

I simply don't understand how this will work.

**Comment by dikeert** [comment]
@et304383 Ah, I see. I think you looking for this: 

> By specifying a VPC security group as the source, you allow incoming traffic from all instances (typically application servers) that use the source VPC security group

from [there](http://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Overview.RDSSecurityGroups.html#Overview.RDSSecurityGroups.VPCSec)

And what we do is this:

```json
    "SecurityGroupIngress": {
      "Type": "AWS::EC2::SecurityGroupIngress",
      "Properties": {
        "GroupId": {
          "Ref": "SecurityGroup"
        },
        "IpProtocol": "-1",
        "FromPort": "-1",
        "ToPort": "-1",
        "SourceSecurityGroupId": {
          "Ref": "SecurityGroup"
        }
      }
    }
```

Notice "SourceSecurityGroupId", it basically references itself as source, therefore all of the EC2 instances in this Security Group is able to access RDS.

As a result you have resource group which looks like [this](http://imgur.com/a/ORRpH)
<img width="422" alt="screen shot 2017-08-18 at 11 32 13 am" src="https://user-images.githubusercontent.com/2032667/29440519-06caa4aa-8409-11e7-9613-a56f70b46adb.png">

**Comment by et304383** [comment]
I see now.  The documentation isn't immediately clear what specifying -1 for the protocol translates to.

In my opinion, there should be a separate security group for each tier of an application.  I think there should be a dedicated "database listener" security group allowing the exact port that the DB is running on.  This is just a security best practice to only allow ports that are necessary on the server being exposed.

**Comment by avattathil** [comment]
Closing out ticket
