### ISSUE TITLE
Using SSL ACM instead of SSL IAM 

### ISSUE THREAD

**Issue by RogerSik** [aws-quickstart/quickstart-atlassian-jira#18]
Hello,

can the template be updated to use SSL ACM Certificates?

Greetings
Roger

**Comment by RogerSik** [comment]
mangelino did the changes:
https://github.com/mangelino/quickstart-atlassian-jira/commit/bb105c80936cbe1fbc867bf4d5cfbc0577011b6a

Can this be please merged?

**Comment by jazzl0ver** [comment]
also fixed in PR #27

**Comment by tonynv** [comment]
cleaning up old issues
