### ISSUE TITLE
Fails on creating postgres db using quickstart template.

### ISSUE THREAD

**Issue by thaumos** [aws-quickstart/quickstart-atlassian-jira#21]
Cannot find version 9.3.12 for postgres (Service: AmazonRDS; Status Code: 400; Error Code: InvalidParameterCombination

When attempting to provision using quickstart template.

**Comment by thaumos** [comment]
https://github.com/aws-quickstart/quickstart-atlassian-jira/blob/04ac0a4c6d13919c445f812c4842acfd8a8ba2ce/templates/JiraDataCenter.template#L894

**Comment by DesHorsley** [comment]
AWS are in the process of phasing out support for 9.3, following the PostgreSQL community announcing that it is end of life as at September 2018. 

Apparently they are disabling the ability to create new 9.3 databases using the console and will do the same with the cli.

They recommend upgrading to 9.6, is there a plan to update the quick starts?

**Comment by tonynv** [comment]
cleaning up old issues
