### ISSUE TITLE
the templates do not work with 7.12.3

### ISSUE THREAD

**Issue by seb-steuer** [aws-quickstart/quickstart-atlassian-jira#28]
Hi,

I believe the templates do not work with 7.12.3 due to server.xml changes related to relaxedQueryChars.
Because you modify server.xml using functions from /etc/init.d/atl-functions you would need to bake new AMI

I believe you should consider simplifying the bootstrapping and include the bootstrapping scripts as part of CFormation file and use vanilla AMIs instead of relying on custom build AMIs you very rarely update anyway so they come with tons of security updates needed. 

kind regards
Sebastian

**Comment by seb-steuer** [comment]
https://jira.atlassian.com/browse/JRASERVER-68116

**Comment by tonynv** [comment]
cleaning old-issues
