### ISSUE TITLE
Customers requesting version 7.3.6

### ISSUE THREAD

**Issue by avattathil** [aws-quickstart/quickstart-atlassian-jira#7]
Quickstart is limited to version 7.2.3.  Customers would like the ability to use version 7.3.6

**Comment by groorj** [comment]
Hi @avattathil. Having the option to use version 7.3.6 is good but if I may suggest, the template should give the option to pick a version (Confluence's template does that). It should be generic enough and not need to be changed for each new version. Thank's, Gus.

**Comment by avattathil** [comment]
Fixes this issue https://github.com/aws-quickstart/quickstart-atlassian-jira/commit/025dc4f96402bd62fe3da0d7ef0770a4b620dbfb

**Comment by avattathil** [comment]
@groorj With the last update from Atlassian the quickstart forces the latest version.
